spring:
  datasource:
    url: jdbc:postgresql://localhost:30000/clever
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true

server:
  servlet:
    context-path: /clever
  port: 8081
logging:
  level:
    org.springframework.security: debug
  controller:
    enable: true